# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /blog/:title

author:
  name:           'Gurjot Sidhu'
  url:            https://twitter.com/gurjotsidhu
  email:	  gsidhu22@gmail.com

paginate:         5
paginate_path: 	  "/blog/page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gsidhu/gsidhu.github.io


