# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:title

author:
  name:           'Gurjot Sidhu'
  url:            https://gsidhu.github.io
  email:	  	  gsidhu22@gmail.com

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/gsidhu/gsidhu.github.io

